# Change these first
owner: dashpan # Your GitHub organization or username, where this repository lives
repo: dashpan-status # The name of this repository

sites:
  - name: API (Produção)
    url: https://api-dash.agenciapan.com
  - name: API (Homologação)
    url: https://api-dashteste.agenciapan.com
  - name: API (MAHAV)
    url: https://api-mahav.dashpan.com
  - name: API (PowerBee)
    url: https://api-powerbee.dashpan.com
  - name: App (Produção)
    url: https://dash.agenciapan.com
  - name: App (Homologação)
    url: https://dashteste.agenciapan.com
  - name: App (MAHAV)
    url: https://mahav.dashpan.com
  - name: App (Powerbee)
    url: https://powerbee.dashpan.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /dashpan-status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Dashpan
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
