# Change these first
owner: dashpan # Your GitHub organization or username, where this repository lives
repo: dashpan.github.io # The name of this repository

sites:
  - name: API (Produção)
    url: https://api-pan.dashpan.com/status
  - name: API (Homologação)
    url: https://api-teste.dashpan.com/status
  - name: API (BOWE)
    url: https://api-bowe.dashpan.com/status
  - name: API (PowerBee)
    url: https://api-powerbee.dashpan.com/status
  - name: App (Produção)
    url: https://pan.dashpan.com
  - name: App (Homologação)
    url: https://teste.dashpan.com
  - name: App (BOWE)
    url: https://bowe.dashpan.com
  - name: App (Powerbee)
    url: https://powerbee.dashpan.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.dashpan.com
  baseUrl: /
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Dashpan
  introTitle:
  introMessage:
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
